### ISSUE TITLE
安装MarkupSafe 1.0报错，建议换更新的版本

### ISSUE THREAD

**Issue by liushuai05** [bay1/vue-admin-flask-example#2]
报错内容如下：
```
  Using cached MarkupSafe-1.0.tar.gz (14 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-1zbob94n/markupsafe_a210681fe389461e9262dfb8c17fce14/setup.py", line 6, in <module>
          from setuptools import setup, Extension, Feature
      ImportError: cannot import name 'Feature' from 'setuptools' (/run/media/edison/fd228aaf-b146-4563-aedf-13b3e5f48f20/test_object/vue-admin-flask-example/venv/lib/python3.10/site-packages/setuptools/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by JfanLiu** [comment]
MarkupSafe==1.1.1
参考stackoverflow，我尝试这样更改，成功了
